#!/usr/bin/env python3
"""Print a status table for every known GAMBIT backend interface.
Reads config/gambit_backends.yaml (regenerated by backend_harvester.py) for
the enabled/disabled interface status, and the data file written by
CMakeLists.txt at configure time (TARGETS=<cmake-list>) for the set of
active backend make targets. Walks every Bit's include/src/examples tree
to find which Bits reference each backend. Prints one row per canonical
BACKENDNAME with its status, a "used by:" list of Bits, and the
backend's user-invokable make targets.
"""
from __future__ import print_function

import io
import os
import sys

import yaml

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.normpath(os.path.join(_HERE, "..", "..", "Utils", "scripts")))

from harvesting_tools import (  # noqa: E402
    compute_bits_per_backend,
    get_all_backendnames,
)


def main():
    if len(sys.argv) != 2:
        sys.stderr.write("Usage: list_backends.py <data_file>\n")
        sys.exit(2)

    active_targets = []
    with io.open(sys.argv[1], "r") as f:
        for line in f:
            if line.startswith("TARGETS="):
                active_targets = [s for s in line[len("TARGETS="):].rstrip("\n").split(";") if s]
                break

    with io.open("./config/gambit_backends.yaml", "r") as f:
        bdata = yaml.safe_load(f) or {}
    enabled_set = set((bdata.get("enabled") or {}).keys())

    frontend_dir = "./Backends/include/gambit/Backends/frontends"
    all_backends = get_all_backendnames(frontend_dir)
    bits_per = compute_bits_per_backend(".", frontend_dir)

    # Group each active target under its longest-matching canonical (so e.g.
    # darksusy_MSSM_6.4.0 lands under DarkSUSY_MSSM, not under DarkSUSY).
    canonicals_by_len = sorted(all_backends, key=len, reverse=True)
    targets_by_canonical = {b: [] for b in all_backends}
    for t in active_targets:
        tl = t.lower()
        for canonical in canonicals_by_len:
            if tl.startswith(canonical.lower() + "_"):
                targets_by_canonical[canonical].append(t)
                break

    rows = []
    for canonical in sorted(all_backends, key=lambda s: s.lower()):
        targets = sorted(targets_by_canonical[canonical])
        active = canonical in enabled_set
        bits = bits_per.get(canonical, [])
        rows.append((canonical, active, bits, targets))

    name_w = max(len(r[0]) for r in rows)
    bits_w = max(len(", ".join(r[2]) if r[2] else "(none)") for r in rows)
    use_color = sys.stdout.isatty()
    YELLOW = "\033[33m" if use_color else ""
    RESET  = "\033[0m" if use_color else ""

    for name, active, bits, targets in rows:
        bits_str    = ", ".join(bits)    if bits    else "(none)"
        targets_str = ", ".join(targets) if targets else "(none)"
        if active:
            tag = " " * 10                    # blank slot, same width as [disabled]
        else:
            tag = YELLOW + "[disabled]" + RESET
        print("  {name:<{nw}}  {tag}  used by: {bits:<{bw}}  targets: {tgts}".format(
            name=name, nw=name_w, tag=tag, bits=bits_str, bw=bits_w, tgts=targets_str))


if __name__ == "__main__":
    main()