//   GAMBIT: Global and Modular BSM Inference Tool
//   *********************************************
///  \file
///
///  Types used internally, returned and/or read
///  in by more than one backend, model or module.
///
///  *********************************************
///
///  Authors (add name and date if you modify):
///
///  \author Pat Scott
///          (patscott@physics.mcgill.ca)
///  \date 2013 Apr, Oct
///  \date 2014 Mar, Sep, Nov
///  \date 2015 Jan, Mar
///
///  \author Abram Krislock
///          (abram.krislock@fysik.su.se)
///  \date 2013 Dec
///
///  \author Christoph Weniger
///          (c.weniger@uva.nl)
///  \date 2014 Mar
///
///  \author Ben Farmer
///          (benjamin.farmer@imperial.ac.uk)
///  \date 2015 Apr, 2019 Jul
///
///  \author Sebastian Wild
///          (sebastian.wild@ph.tum.de)
///  \date 2016 Aug
///
///  \author Sanjay Bloor
///          (sanjay.bloor12@imperial.ac.uk)
///  \date 2017 Aug
///
///  *********************************************

#ifndef __shared_types_hpp__
#define __shared_types_hpp__

// The bulk of the shared types now live in shared_types_core.hpp, which
// deliberately excludes the (heavy, auto-generated) full set of backend types.
// shared_types.hpp == shared_types_core.hpp + backend_types_rollcall.hpp, so
// every existing includer of shared_types.hpp sees exactly the same set of
// types as before this header was split.
#include "gambit/Elements/shared_types_core.hpp"               // All shared types except the full backend type set
#include "gambit/Backends/backend_types_rollcall.hpp"          // All backend types (header is auto-generated by backend harvester).


#endif //__shared_types_hpp__
