#!/usr/bin/env python3
"""
preprocess_size.py - Measure preprocessed source expansion for GAMBIT.

Runs the C++ preprocessor on each translation unit and measures how many lines
and bytes the compiler actually has to parse.  Large expansion ratios indicate
header bloat — a prime cause of slow compilation.

Also detects repeated textual inclusion of the same header content (headers
lacking or having broken include guards) by comparing the -H include tree
against what a correct once-only inclusion would produce.

Requires: a C++ compiler accessible on PATH (g++ or clang++) and, ideally,
a compile_commands.json generated by CMake.  Without compile_commands.json the
script falls back to a best-effort set of default flags.

Usage:
    python3 scripts/build_profiling/preprocess_size.py [OPTIONS]

Options:
    --build-dir DIR     CMake build directory containing compile_commands.json
    --root DIR          GAMBIT source root (auto-detected if not given)
    --compiler CMD      Compiler to use, e.g. g++, clang++ (default: auto)
    --module MODULE     Restrict to one module, e.g. DarkBit
    --jobs N            Parallel workers (default: half the CPU count)
    --top N             Show top N files (default: 30)
    --output FILE       Write JSON summary to FILE
    --include-tree      Also emit a per-file include tree (slow, uses -H flag)

Examples:
    # After running: cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
    python3 scripts/build_profiling/preprocess_size.py --build-dir build/

    # Without a build dir (uses default flags):
    python3 scripts/build_profiling/preprocess_size.py --module DarkBit

    # Full analysis with include trees, save JSON:
    python3 scripts/build_profiling/preprocess_size.py --build-dir build/ --include-tree --output pp_results.json
"""

import argparse
import collections
import concurrent.futures
import json
import os
import re
import shutil
import subprocess
import sys
import time
from pathlib import Path


GAMBIT_MODULES = [
    'Core', 'Utils', 'Elements', 'Models', 'Logs', 'Printers', 'ScannerBit',
    'DarkBit', 'ColliderBit', 'NeutrinoBit', 'DecayBit', 'FlavBit',
    'SpecBit', 'PrecisionBit', 'CosmoBit', 'ObjectivesBit',
    'ExampleBit_A', 'ExampleBit_B', 'Backends', 'gum',
]


def find_root() -> Path:
    here = Path(__file__).resolve()
    for parent in [here, *here.parents]:
        if (parent / 'CMakeLists.txt').exists() and (parent / 'Core').exists():
            return parent
    sys.exit("ERROR: Could not find GAMBIT root. Pass --root.")


def find_compiler() -> str:
    for cmd in ('clang++', 'g++', 'c++'):
        if shutil.which(cmd):
            return cmd
    sys.exit("ERROR: No C++ compiler found on PATH. Install g++ or clang++.")


def load_compile_commands(build_dir: Path) -> dict[str, dict]:
    """Load compile_commands.json and return a map from source file -> entry."""
    cc_path = build_dir / 'compile_commands.json'
    if not cc_path.exists():
        return {}
    with open(cc_path) as fh:
        entries = json.load(fh)
    result = {}
    for entry in entries:
        src = Path(entry.get('file', '')).resolve()
        result[str(src)] = entry
    return result


def flags_from_compile_command(entry: dict) -> list[str]:
    """Extract include paths and defines from a compile_commands.json entry."""
    cmd = entry.get('command', '')
    if not cmd:
        args = entry.get('arguments', [])
        cmd = ' '.join(args)
    flags = []
    # Extract -I, -D, -isystem, -std flags
    tokens = cmd.split()
    skip_next = False
    for i, tok in enumerate(tokens):
        if skip_next:
            skip_next = False
            continue
        if tok in ('-o', '-c', '-MF', '-MT', '-MQ'):
            skip_next = True
            continue
        if tok.startswith(('-I', '-D', '-isystem', '-std=', '-U',
                           '-include', '-iquote', '-idirafter')):
            flags.append(tok)
        elif tok in ('-isystem', '-include', '-iquote', '-idirafter', '-I'):
            # Separated form: -isystem /path
            if i + 1 < len(tokens):
                flags.append(tok)
                flags.append(tokens[i + 1])
                skip_next = True
    return flags


def default_flags(root: Path) -> list[str]:
    """Best-effort flags when no compile_commands.json is available."""
    flags = ['-std=c++17', f'-I{root}', f'-I{root}/Core/include',
             f'-I{root}/Utils/include', f'-I{root}/Elements/include']
    # Add all module includes
    for mod in GAMBIT_MODULES:
        inc = root / mod / 'include'
        if inc.exists():
            flags += [f'-I{inc}']
    # contrib yaml-cpp
    yaml_inc = root / 'contrib' / 'yaml-cpp-0.6.2' / 'include'
    if yaml_inc.exists():
        flags += [f'-I{yaml_inc}']
    return flags


def find_translation_units(root: Path, module: str | None) -> list[Path]:
    units = []
    skip_dirs = {'build', '.git', 'contrib', '.github'}
    for dirpath, dirnames, filenames in os.walk(root):
        dp = Path(dirpath)
        dirnames[:] = [d for d in dirnames if d not in skip_dirs]
        rel = dp.relative_to(root)
        parts = rel.parts
        if module and parts and parts[0] != module:
            dirnames.clear()
            continue
        for fn in filenames:
            if Path(fn).suffix.lower() in {'.cpp', '.cc', '.cxx'}:
                units.append(dp / fn)
    return units


# ---------------------------------------------------------------------------
# Per-file preprocessing
# ---------------------------------------------------------------------------

INCLUDE_LINE_RE = re.compile(r'^(\s+\.*)\s(.+)$')  # from -H output


def preprocess_file(args_tuple) -> dict:
    """Run the preprocessor on one file; return metrics dict."""
    src, compiler, extra_flags, include_tree = args_tuple
    src_path = Path(src)

    cmd_base = [compiler, '-E'] + extra_flags + [str(src_path)]
    # Suppress output, just count
    try:
        result = subprocess.run(
            cmd_base + ['-o', '/dev/null', '-w'],
            capture_output=True, text=True, timeout=120,
        )
        # Rerun to count lines/bytes
        result2 = subprocess.run(
            cmd_base,
            capture_output=True, timeout=120,
        )
        pp_bytes = len(result2.stdout)
        pp_lines = result2.stdout.count(b'\n')
    except subprocess.TimeoutExpired:
        return {'file': src, 'error': 'timeout'}
    except Exception as e:
        return {'file': src, 'error': str(e)}

    orig_bytes = src_path.stat().st_size

    entry = {
        'file': src,
        'orig_bytes': orig_bytes,
        'pp_bytes': pp_bytes,
        'pp_lines': pp_lines,
        'expansion_ratio': pp_bytes / orig_bytes if orig_bytes else 0,
    }

    if include_tree:
        # Use -H to get include hierarchy (stderr)
        try:
            h_result = subprocess.run(
                [compiler, '-E', '-H', '-o', '/dev/null'] + extra_flags + [str(src_path)],
                capture_output=True, text=True, timeout=180,
            )
            includes = []
            for line in h_result.stderr.splitlines():
                m = INCLUDE_LINE_RE.match(line)
                if m:
                    depth = len(m.group(1).strip('.'))
                    includes.append({'depth': depth, 'path': m.group(2).strip()})
            entry['include_tree'] = includes
            # Count how many times each header appears (re-inclusion without guards)
            path_counts: dict[str, int] = collections.Counter(i['path'] for i in includes)
            entry['repeated_headers'] = {p: c for p, c in path_counts.items() if c > 1}
        except Exception:
            pass

    return entry


# ---------------------------------------------------------------------------
# Reporting
# ---------------------------------------------------------------------------

def module_of(path_str: str) -> str:
    parts = Path(path_str).parts
    # Find the module component
    for i, p in enumerate(parts):
        if p in GAMBIT_MODULES:
            return p
    return 'other'


def fmt_bytes(n: int) -> str:
    if n >= 1_048_576:
        return f"{n/1_048_576:.1f} MB"
    if n >= 1_024:
        return f"{n/1_024:.1f} KB"
    return f"{n} B"


def print_section(title: str):
    print()
    print("=" * 72)
    print(f"  {title}")
    print("=" * 72)


def report(results: list[dict], root: Path, top_n: int):
    ok = [r for r in results if 'error' not in r]
    errors = [r for r in results if 'error' in r]

    print_section("GAMBIT Preprocessed Source Size Analysis")
    print(f"  Files processed: {len(ok)} ok, {len(errors)} errors")
    if ok:
        total_orig = sum(r['orig_bytes'] for r in ok)
        total_pp = sum(r['pp_bytes'] for r in ok)
        print(f"  Total original source:        {fmt_bytes(total_orig)}")
        print(f"  Total preprocessed output:    {fmt_bytes(total_pp)}")
        print(f"  Overall expansion ratio:      {total_pp/total_orig:.1f}x")

    print_section(f"Top {top_n} files by preprocessed SIZE (most compiler work)")
    print(f"  {'PP size':>9}  {'Orig':>9}  {'Ratio':>6}  {'Module':<16}  File")
    print(f"  {'-'*9}  {'-'*9}  {'-'*6}  {'-'*16}  {'-'*36}")
    for r in sorted(ok, key=lambda x: -x['pp_bytes'])[:top_n]:
        rel = Path(r['file'])
        try:
            rel = rel.relative_to(root)
        except ValueError:
            pass
        mod = module_of(str(rel))
        print(f"  {fmt_bytes(r['pp_bytes']):>9}  {fmt_bytes(r['orig_bytes']):>9}  "
              f"{r['expansion_ratio']:>5.0f}x  {mod:<16}  {rel}")

    print_section(f"Top {top_n} files by EXPANSION RATIO (most relative header bloat)")
    print(f"  {'Ratio':>6}  {'PP size':>9}  {'Orig':>7}  {'Module':<16}  File")
    print(f"  {'-'*6}  {'-'*9}  {'-'*7}  {'-'*16}  {'-'*36}")
    for r in sorted(ok, key=lambda x: -x['expansion_ratio'])[:top_n]:
        rel = Path(r['file'])
        try:
            rel = rel.relative_to(root)
        except ValueError:
            pass
        mod = module_of(str(rel))
        print(f"  {r['expansion_ratio']:>5.0f}x  {fmt_bytes(r['pp_bytes']):>9}  "
              f"{fmt_bytes(r['orig_bytes']):>7}  {mod:<16}  {rel}")

    # --- Per-module summary ---
    print_section("Per-module preprocessed size summary")
    by_mod: dict[str, list[dict]] = collections.defaultdict(list)
    for r in ok:
        rel = Path(r['file'])
        try:
            rel = rel.relative_to(root)
        except ValueError:
            pass
        by_mod[module_of(str(rel))].append(r)

    print(f"  {'Module':<20}  {'Files':>5}  {'TotalPP':>10}  {'AvgPP':>9}  {'AvgRatio':>9}")
    print(f"  {'-'*20}  {'-'*5}  {'-'*10}  {'-'*9}  {'-'*9}")
    for mod in sorted(by_mod, key=lambda m: -sum(r['pp_bytes'] for r in by_mod[m])):
        rs = by_mod[mod]
        total_pp = sum(r['pp_bytes'] for r in rs)
        avg_pp = total_pp / len(rs)
        avg_ratio = sum(r['expansion_ratio'] for r in rs) / len(rs)
        print(f"  {mod:<20}  {len(rs):>5}  {fmt_bytes(total_pp):>10}  "
              f"{fmt_bytes(int(avg_pp)):>9}  {avg_ratio:>8.0f}x")

    # --- Repeated headers ---
    all_repeated: dict[str, int] = collections.Counter()
    if any('repeated_headers' in r for r in ok):
        print_section("Headers included multiple times per TU (missing/broken include guards)")
        print("  (Each row = a header included >1 time in at least one TU)")
        for r in ok:
            for hdr, cnt in r.get('repeated_headers', {}).items():
                all_repeated[hdr] = max(all_repeated[hdr], cnt)
        if all_repeated:
            print(f"  {'MaxRep':>6}  Header")
            print(f"  {'-'*6}  {'-'*64}")
            for hdr, cnt in sorted(all_repeated.items(), key=lambda x: -x[1])[:top_n]:
                print(f"  {cnt:>6}  {hdr}")
        else:
            print("  None detected - all headers appear properly guarded.")

    if errors:
        print_section(f"Errors ({len(errors)} files failed)")
        for r in errors[:20]:
            print(f"  {r['file']}: {r.get('error', '?')}")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Measure preprocessed source expansion for GAMBIT.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument('--build-dir', default=None, help='CMake build dir with compile_commands.json')
    parser.add_argument('--root', default=None)
    parser.add_argument('--compiler', default=None)
    parser.add_argument('--module', default=None)
    parser.add_argument('--jobs', type=int, default=max(1, os.cpu_count() // 2))
    parser.add_argument('--top', type=int, default=30)
    parser.add_argument('--output', default=None)
    parser.add_argument('--include-tree', action='store_true',
                        help='Also collect per-file include trees (slower)')
    args = parser.parse_args()

    root = Path(args.root).resolve() if args.root else find_root()
    compiler = args.compiler or find_compiler()
    build_dir = Path(args.build_dir).resolve() if args.build_dir else None

    print(f"Compiler: {compiler}")
    print(f"Root: {root}")

    compile_commands = {}
    if build_dir:
        compile_commands = load_compile_commands(build_dir)
        print(f"Loaded {len(compile_commands)} entries from compile_commands.json")

    units = find_translation_units(root, args.module)
    print(f"Found {len(units)} translation units to process")
    if not units:
        sys.exit("No translation units found. Check --module spelling.")

    fallback = default_flags(root)

    tasks = []
    for u in units:
        key = str(u.resolve())
        if key in compile_commands:
            flags = flags_from_compile_command(compile_commands[key])
        else:
            flags = fallback
        tasks.append((str(u), compiler, flags, args.include_tree))

    print(f"Running preprocessor with {args.jobs} parallel workers ...")
    t0 = time.time()
    results = []
    with concurrent.futures.ProcessPoolExecutor(max_workers=args.jobs) as ex:
        futures = {ex.submit(preprocess_file, t): t for t in tasks}
        done = 0
        for fut in concurrent.futures.as_completed(futures):
            results.append(fut.result())
            done += 1
            if done % 50 == 0 or done == len(tasks):
                elapsed = time.time() - t0
                rate = done / elapsed
                eta = (len(tasks) - done) / rate if rate else 0
                print(f"  {done}/{len(tasks)} files  {elapsed:.0f}s elapsed  ETA {eta:.0f}s",
                      end='\r', flush=True)
    print()
    print(f"Preprocessing complete in {time.time()-t0:.1f}s")

    report(results, root, args.top)

    if args.output:
        out_path = Path(args.output)
        # Strip large trees for JSON to keep it manageable
        json_results = []
        for r in results:
            jr = {k: v for k, v in r.items() if k != 'include_tree'}
            # Truncate repeated_headers if huge
            json_results.append(jr)
        out_path.write_text(json.dumps(json_results, indent=2))
        print(f"\nJSON results written to {out_path}")


if __name__ == '__main__':
    main()
